'use client';

import { useState } from 'react';

const faqs = [
  {
    q: 'What file formats can I download my logo in?',
    a: 'You can download your logo in SVG (vector format, infinitely scalable) and PNG (1024x1024px, optimized for web and print). SVG is recommended for professional use.',
  },
  {
    q: 'Are the logos truly unique?',
    a: 'Yes! Each logo is generated algorithmically based on your inputs — brand name, industry, style, color palette, and pattern. The combination of parameters ensures unique results every time.',
  },
  {
    q: 'Can I use the logos commercially?',
    a: 'Absolutely! All logos generated by LixStudio are yours to use for any purpose — commercial, personal, or otherwise. No attribution required.',
  },
  {
    q: 'How does the SVG generation engine work?',
    a: 'Our engine uses 7 core design patterns: dot matrices, geometric shapes, line systems, node networks, and 3 combination patterns. Each pattern has mathematical parameters that adapt to your style and industry selection.',
  },
  {
    q: 'Can I customize colors beyond the preset palettes?',
    a: 'Pro users can input custom hex colors and create their own palettes. Free users have access to our curated industry-specific color palettes.',
  },
  {
    q: 'What are the logo variants?',
    a: 'We generate 4 variants: icon-only (standalone mark), wordmark (icon + name side by side), stacked (icon on top, name below), and horizontal (name with icon). Each is optimized for different use cases.',
  },
];

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  return (
    <section id="faq" className="py-24 px-4">
      <div className="max-w-3xl mx-auto">
        <div className="text-center mb-16">
          <span className="text-sm text-violet-400 font-medium tracking-wider uppercase">FAQ</span>
          <h2 className="text-3xl sm:text-4xl font-bold text-white mt-3 mb-4">
            Frequently Asked Questions
          </h2>
          <p className="text-gray-400">
            Everything you need to know about LixStudio Logo Generator.
          </p>
        </div>

        <div className="space-y-3">
          {faqs.map((faq, i) => (
            <div
              key={i}
              className="rounded-xl border border-gray-800/50 overflow-hidden"
            >
              <button
                onClick={() => setOpenIndex(openIndex === i ? null : i)}
                className="w-full flex items-center justify-between px-6 py-4 text-left bg-gray-900/30 hover:bg-gray-900/50 transition-colors"
              >
                <span className="text-sm font-medium text-white pr-4">{faq.q}</span>
                <svg
                  className={`w-5 h-5 text-gray-400 flex-shrink-0 transition-transform duration-200 ${
                    openIndex === i ? 'rotate-180' : ''
                  }`}
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                  strokeWidth="2"
                >
                  <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" />
                </svg>
              </button>
              {openIndex === i && (
                <div className="px-6 py-4 bg-gray-900/20 border-t border-gray-800/30">
                  <p className="text-sm text-gray-400 leading-relaxed">{faq.a}</p>
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
